"""
Content Expander

Expands outline sections into full content using LLM.
"""

import sys
import os

# Add src to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

from src.content_generator.llm_client import get_llm_client
from src.product_generator.outline_builder import ProductOutline

class ContentExpander:
    def __init__(self):
        self.llm_client = get_llm_client()
    
    def expand_section(self, section_title: str, items: list, topic: str, product_type: str) -> str:
        """Expand a single section with AI-generated content."""
        
        # Build context-aware prompt
        prompt = f"""You are creating content for a digital product about "{topic}".
Product type: {product_type}

Section: {section_title}
Outline items:
{chr(10).join(['- ' + item for item in items])}

Expand this section with:
- Actionable, specific advice
- Real examples and tools
- Clear, concise language
- Practical tips solopreneurs can use immediately

Write 2-3 paragraphs of valuable content for this section."""

        content = self.llm_client.generate_text(prompt)
        return content
    
    def expand_outline(self, outline: ProductOutline, topic: str) -> str:
        """Expand entire outline into full markdown content."""
        
        full_content = f"# {outline.title}\n\n"
        full_content += f"*A comprehensive {outline.product_type} for {topic}*\n\n"
        full_content += "---\n\n"
        
        for section in outline.sections:
            section_title = section['title']
            items = section.get('items', [])
            
            full_content += f"## {section_title}\n\n"
            
            # Expand with AI
            expanded = self.expand_section(section_title, items, topic, outline.product_type)
            full_content += expanded + "\n\n"
            
            # Add original items as bullet points
            if items:
                for item in items:
                    full_content += f"- {item}\n"
                full_content += "\n"
        
        # Add footer
        full_content += "---\n\n"
        full_content += "*Generated by AI Solopreneur Bot*\n"
        
        return full_content
